import { Inter } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import InitProvider from '@/utils/providers/init-provider'

const inter = Inter({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <InitProvider>
          {children}
        </InitProvider>
        <script src="https://accounts.google.com/gsi/client">
        </script>
      </body>
    </html>
  )
}
