import { Poppins } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import InitProvider from '@/utils/providers/init-provider'
import { UserProvider } from '@/utils/contexts/user-context'
import 'tippy.js/dist/tippy.css'; // optional

const poppins = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserProvider>
          <InitProvider>
            {children}
          </InitProvider>
        </UserProvider>
        <script src="https://accounts.google.com/gsi/client">
        </script>
      </body>
    </html>
  )
}
